# Generated by Django 5.0.10 on 2025-01-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0648_remove_stream_stream_post_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="welcome_bot_custom_message",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="realm",
            name="welcome_bot_custom_message_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
