# Generated by Django 5.0.10 on 2025-01-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0663_realm_enable_guest_user_dm_warning"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="message_edit_history_visibility",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
