# Generated by Django 5.0.10 on 2025-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0672_fix_attachment_realm"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="message_edit_history_visibility_policy",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
